# Generated by Django 4.1.5 on 2023-02-03 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('shortDescription', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='auction/static/img/items')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('during', 'w trakcie'), ('finished', 'zakończony'), ('new', 'nowy')], default='new', max_length=255)),
                ('maxPrice', models.DecimalField(decimal_places=0, max_digits=10)),
                ('voteDate', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
