# Generated by Django 4.1.5 on 2023-02-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('new', 'nowy'), ('during', 'w trakcie'), ('finished', 'zakończony')], default='new', max_length=255),
        ),
    ]
