# Generated by Django 4.1.5 on 2023-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.TextField(),
        ),
    ]
